# Generated by Django 4.2.1 on 2023-05-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('images', models.ImageField(upload_to='images/')),
                ('colors_types', models.JSONField(default=list, verbose_name=models.CharField(max_length=100))),
                ('description', models.TextField()),
                ('home_page', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
